
# Performing Matrix Manipulations

Matrix manipulation such as performing multiplication, addition, substraction, and imoirtant operations in the propagation of signals in any Neural Network.

### Bellow is the Reciepe to get Defferent Types of Metrices and Perform to Defferent Matrix Manipulation 

<br>

In [82]:
import tensorflow as tf

In [83]:
# start interrative session
sess = tf.InteractiveSession()

/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [84]:
# Define a 5x5 identity matrix
I_matrix = tf.eye(5)
print(I_matrix.eval())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [85]:
# Define a variable initialized to a 10x10 identity matrix
X = tf.Variable(tf.eye(10))
X.initializer.run()                # initialize the variable
print(X.eval())                    # print and evaluate the matrix result

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [86]:
# Create a random matrix 5x10
A = tf.Variable(tf.random_normal([5, 10]))
A.initializer.run()

In [87]:
# Multiply 2 matrices
product = tf.matmul(A, X)
print(product.eval())

[[ 0.3884052  -0.20071217  0.7077306  -1.0082042  -0.80432737 -0.2817233
  -0.2755039   0.9907699   1.4530596   0.9548414 ]
 [-1.1248279  -0.6529643  -1.3081189   0.16997091  0.44064733 -0.69650775
  -0.29731524 -1.4583848   0.4190129  -0.9973541 ]
 [-0.43917242 -1.2171772  -0.56984556 -0.97388965 -1.8356453  -0.28943956
   1.3302768  -0.51041615 -1.0522984   0.2611218 ]
 [-0.07096083 -1.6746392   1.712338   -0.48687685 -1.0357969  -0.9821703
   0.6665854  -0.60496664  0.9915173   0.30854774]
 [ 0.43853614  0.00453601  1.1273719   0.22033477 -2.141151   -0.86472774
  -0.87512803 -0.25846988  0.6987238  -0.7903361 ]]


In [88]:
# Create random matrix of 1s and 0s, size 5x10
b = tf.Variable(tf.random_uniform([5, 10], 0, 2, dtype = tf.int32))
b.initializer.run()
print(b.eval())
b_new = tf.cast(b, dtype = tf.float32)                # Cast or convert to float32 data type

[[0 1 1 1 0 0 1 0 1 0]
 [1 0 0 1 1 0 0 0 1 1]
 [0 1 0 1 1 0 1 0 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 1 0 0]]


In [89]:
# add the two matrices
t_sum = tf.add(product, b_new)
t_sub = product - b_new
print("A * X _b\n", t_sum.eval())
print("\n")
print("A * X _b\n", t_sub.eval())

A * X _b
 [[ 0.3884052   0.7992878   1.7077305  -0.00820422 -0.80432737 -0.2817233
   0.7244961   0.9907699   2.4530597   0.9548414 ]
 [-0.12482786 -0.6529643  -1.3081189   1.1699709   1.4406474  -0.69650775
  -0.29731524 -1.4583848   1.4190129   0.00264591]
 [-0.43917242 -0.21717715 -0.56984556  0.02611035 -0.8356453  -0.28943956
   2.330277   -0.51041615 -0.05229843  0.2611218 ]
 [-0.07096083 -1.6746392   1.712338    0.51312315 -1.0357969  -0.9821703
   0.6665854  -0.60496664  0.9915173   0.30854774]
 [ 1.4385362   1.004536    1.1273719   0.22033477 -2.141151    0.13527226
  -0.87512803  0.7415301   0.6987238  -0.7903361 ]]


A * X _b
 [[ 0.3884052  -1.2007122  -0.2922694  -2.0082042  -0.80432737 -0.2817233
  -1.2755039   0.9907699   0.45305955  0.9548414 ]
 [-2.1248279  -0.6529643  -1.3081189  -0.8300291  -0.55935264 -0.69650775
  -0.29731524 -1.4583848  -0.5809871  -1.997354  ]
 [-0.43917242 -2.2171772  -0.56984556 -1.9738896  -2.8356452  -0.28943956
   0.33027685 -0.51041615 -2.05

## Another way to manipulate matrix

In [90]:
# create two random metrices
a = tf.Variable(tf.random_normal([4, 5], stddev = 2))
b = tf.Variable(tf.random_normal([4, 5], stddev = 2))

In [91]:
# element wise multiplication
A = a * b

In [92]:
# multiplication with a scalar 2
B = tf.scalar_mul(2, A)

In [93]:
# element wise devision, its result is
C = tf.div(a, b)
C_td = tf.truediv(a, b)

In [94]:
# element wise remainder of devision
D = tf.mod(a, b)

In [95]:
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    writer = tf.summary.FileWriter('graphs', sess.graph)
    a,b,A_R, B_R, C_R, C_TD, D_R = sess.run([a, b, A, B, C, C_td, D])
    print("a\n", a, "\nb\n", b, "\na*b\n", A_R, "\n2*a*b\n", B_R, "\na/b\n", C_R, "\nTrueDivision of a/b \n", C_TD, "\na%b\n", D_R)
writer.close()

a
 [[-2.0304248   2.664809    2.030393   -1.1922994  -4.747106  ]
 [ 2.7072139  -0.77451897  2.202923   -0.00923556  0.91440624]
 [ 2.3311636  -0.78322816  0.15427448 -0.67948097  1.5896238 ]
 [-1.3588177  -1.7344939  -0.44344935 -1.535561    2.1635058 ]] 
b
 [[-2.6920936  -1.919947    1.0417008  -0.8933185   0.452902  ]
 [ 2.8179696  -3.0387573  -1.5328101  -1.0069878  -1.0512807 ]
 [ 2.4982374   1.0281675  -1.4869343   2.2904055   1.2379968 ]
 [ 0.9647091  -0.91824627 -0.86041325  0.62466276  1.1606636 ]] 
a*b
 [[ 5.4660935  -5.116292    2.115062    1.065103   -2.1499739 ]
 [ 7.628846    2.3535752  -3.3766627   0.00930009 -0.9612977 ]
 [ 5.8238     -0.80528975 -0.22939602 -1.5562869   1.9679493 ]
 [-1.3108639   1.5926925   0.3815497  -0.9592078   2.5111024 ]] 
2*a*b
 [[ 10.932187   -10.232584     4.230124     2.130206    -4.2999477 ]
 [ 15.257692     4.7071505   -6.7533255    0.01860018  -1.9225954 ]
 [ 11.6476      -1.6105795   -0.45879203  -3.1125739    3.9358985 ]
 [ -2.6217277   

# Using a Data Flow Grpah [TensorBoard]

In [103]:
# Make a normal distribution, with a shifting mean
mean_moving_normal = tf.random_normal(shape=[1000], mean=(5*k), stddev=1)
# Record that distribution into a histogram summary
tf.summary.histogram("normal/moving_mean", mean_moving_normal)

# Make a normal distribution with shrinking variance
variance_shrinking_normal = tf.random_normal(shape=[1000], mean=0, stddev=1-(k))
# Record that distribution too
tf.summary.histogram("normal/shrinking_variance", variance_shrinking_normal)

# Let's combine both of those distributions into one dataset
normal_combined = tf.concat([mean_moving_normal, variance_shrinking_normal], 0)
# We add another histogram summary to record the combined distribution
tf.summary.histogram("normal/bimodal", normal_combined)

summaries = tf.summary.merge_all()

# Setup a session and summary writer
sess = tf.Session()
writer = tf.summary.FileWriter("/tmp/histogram_example")

# Setup a loop and write the summaries to disk
N = 400
for step in range(N):
  k_val = step/float(N)
  summ = sess.run(summaries, feed_dict={k: k_val})
  writer.add_summary(summ, global_step=step)


# AFTER THIS CODE IS RUNNING THEN :
# OPEN TERMINAL ---> tensorboard --logdir=/tmp/hiistogram_exampole

# Using XLA "Accelerated Linear Algebra" to Enhance Computational Performance


Is a doami-specific compiler for linear algebra. according https://www.tensorflow.org/performance/xla/ and can improve exceution speed, memory usage, and probability on the server and mobile platform.


### XLA is not built-in TensorFlow, we need to build maunaly from source

# SKIPED INSTALLATION